# Deployment variables will only work within deployment steps in bitbucket-pipelines.yaml

image: atlassian/default-image:4
pipelines:
  branches:
    DEV:
      - step:
          script:
            - ssh $USER@$HOST "$PIPELINE_V2 $DIR $PHP81"